dataset:
  root_dir: "/Users/orrav/Documents/Data/ml-climate/OPTIMAL-31"
  shot: 1
  test_way: 5
  test_shot: 1
  test_query: 30
  train_query: 15
  train_way: 10
  train_tasks: 100
  test_tasks: 100

model:
  # facebook/dinov2-base
  # microsoft/resnet-50
  name: "google/vit-base-patch16-224-in21k"
  train: false

training:
  meta: false
  epochs: 100
  batch_size: 32
  lr: 1e-4
  min_lr: 1e-5
  patience: 3
  saved_models_dir: "./output_models"
