dataset:
  root_dir: "/Users/orrav/Documents/Data/ml-climate/EuroSAT/EuroSAT_RGB"
  shot: 1
  test_way: 5
  test_shot: 1
  test_query: 30
  train_query: 15
  train_way: 30
  test_tasks: 600

model:
  name: "google/vit-base-patch16-224-in21k"
  train: false

training:
  meta: false
  epochs: 250
  batch_size: 32
